
from airflow.models import Variable

emailOpenOrc2text = SSHOperator(
    ssh_hook = sshHook,
    task_id='emailOpenOrc2text',
    command="""r'sh -x /home/ebiklondikep/spock/runspockKlondike_minio_subbu1.sh 20190522 20190621 emailOpenOrc2text'+ '{{ Variable.get('Klondikejob_sampleworkflow_exec') }}' +'8G KLONDIKE 0'""",
    # command=r'sh -x /home/ebiklondikep/spock/runspockKlondike_minio_subbu1.sh 20190522 20190621 emailOpenOrc2text'+ '{{ Variable.get('Klondikejob_sampleworkflow_exec') }}' +'8G KLONDIKE 0',
    params={'s_mth':s_mth,'e_mth':e_mth},
    trigger_rule='all_success',
    #append_env=True,
    dag=dag
)


Log:
*** Reading remote log from Cloudwatch log_group: airflow-airflow-ebi-lower-Task log_stream: Klondikejob_sampleworkflow/emailOpenOrc2text/2022-11-07T21_58_49.974123+00_00/1.log.
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1035}} INFO - Dependencies all met for <TaskInstance: Klondikejob_sampleworkflow.emailOpenOrc2text manual__2022-11-07T21:58:49.974123+00:00 [queued]>
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1035}} INFO - Dependencies all met for <TaskInstance: Klondikejob_sampleworkflow.emailOpenOrc2text manual__2022-11-07T21:58:49.974123+00:00 [queued]>
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1241}} INFO - 
--------------------------------------------------------------------------------
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1242}} INFO - Starting attempt 1 of 1
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1243}} INFO - 
--------------------------------------------------------------------------------
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1262}} INFO - Executing <Task(SSHOperator): emailOpenOrc2text> on 2022-11-07 21:58:49.974123+00:00
[2022-11-07, 21:58:51 UTC] {{standard_task_runner.py:52}} INFO - Started process 2838 to run task
[2022-11-07, 21:58:51 UTC] {{standard_task_runner.py:76}} INFO - Running: ['airflow', 'tasks', 'run', 'Klondikejob_sampleworkflow', 'emailOpenOrc2text', 'manual__2022-11-07T21:58:49.974123+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/klondikejob_sampleworkflow.py', '--cfg-path', '/tmp/tmps9cbrn1p', '--error-file', '/tmp/tmp0_6yqn9l']
[2022-11-07, 21:58:51 UTC] {{standard_task_runner.py:77}} INFO - Job 349: Subtask emailOpenOrc2text
[2022-11-07, 21:58:51 UTC] {{logging_mixin.py:109}} INFO - Running <TaskInstance: Klondikejob_sampleworkflow.emailOpenOrc2text manual__2022-11-07T21:58:49.974123+00:00 [running]> on host ip-10-141-81-231.ec2.internal
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1703}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1421, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2113, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1057, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1070, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1107, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'Variable' is undefined
[2022-11-07, 21:58:51 UTC] {{taskinstance.py:1280}} INFO - Marking task as FAILED. dag_id=Klondikejob_sampleworkflow, task_id=emailOpenOrc2text, execution_date=20221107T215849, start_date=20221107T215851, end_date=20221107T215851
[2022-11-07, 21:58:51 UTC] {{standard_task_runner.py:91}} ERROR - Failed to execute job 349 for task emailOpenOrc2text
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1421, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2113, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1057, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1070, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1107, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'Variable' is undefined
[2022-11-07, 21:58:51 UTC] {{local_task_job.py:154}} INFO - Task exited with return code 1
[2022-11-07, 21:58:51 UTC] {{local_task_job.py:264}} INFO - 0 downstream tasks scheduled from follow-on schedule check


